backend:
  name: github
  repo: adamavenir/code-423n4.github.io
  branch: cms

local_backend: true

publish-mode: editorial_workflow

media_folder: "/static/images"
public_folder: "/images"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: people
    label: Handles
    label_singular: Handle
    slug: "{{name}}"
    folder: "data/people"
    media_folder: "{{media_folder}}/people"
    public_folder: "{{public_folder}}/orgs"
    identifier_field: "name"
    create: true
    extension: json
    fields:
      - { name: name, label: Name, required: true }
      - { name: link, label: Link, required: true }
      - { name: image, label: Image, widget: image, required: true }
  - name: org
    label: Organizations
    label_singular: Organization
    slug: "{{name}}"
    folder: "data/orgs"
    media_folder: "{{media_folder}}/orgs"
    public_folder: "{{public_folder}}/orgs"
    identifier_field: "name"
    create: true
    extension: json
    fields:
      - { name: name, label: Name, required: true }
      - { name: link, label: Link, required: true }
      - { name: image, label: Image, widget: image, required: true }
  - name: contests
    label: Contests
    label_singular: Contests
    slug: "{{title}}"
    folder: "data/contests"
    media_folder: "{{media_folder}}/contests"
    public_folder: "{{public_folder}}/contests"
    identifier_field: "title"
    create: true
    extension: json
    fields:
      - {
          name: sponsor,
          label: Sponsor,
          widget: relation,
          required: true,
          multiple: false,
          collection: "org",
          searchFields: ["name"],
          valueField: "name",
          displayFields: ["name"],
        }
      - {
          name: start_time,
          label: "Start time",
          widget: datetime,
          required: false,
        }
      - {
          name: end_time,
          label: "Start time",
          widget: datetime,
          required: false,
        }
      - { name: title, label: Title, required: true }
      - { name: details, label: Details, widget: markdown, required: false }
      - {
          name: wardens,
          label: Wardens,
          widget: relation,
          required: false,
          multiple: true,
          collection: "people",
          searchFields: ["name"],
          valueField: "name",
          displayFields: ["name"],
        }
      - {
          name: judges,
          label: Judges,
          widget: relation,
          required: false,
          multiple: true,
          collection: "people",
          searchFields: ["name"],
          valueField: "name",
          displayFields: ["name"],
        }
      - { name: id, label: ID, widget: ncw-id }
      - { name: hide, label: "Hide?", widget: boolean, required: false }
  - name: findings
    label: Findings
    label_singular: Findings
    slug: "contest-{{contest}}-"
    folder: "data/findings"
    media_folder: "{{media_folder}}/findings"
    public_folder: "{{public_folder}}/findings"
    identifier_field: "id"
    create: true
    extension: json
    fields:
      - {
          name: contest,
          label: Contest,
          widget: relation,
          required: true,
          multiple: false,
          collection: "contest",
          searchFields: ["title"],
          valueField: "id",
          displayFields: ["title"],
        }
      - {
          name: severity,
          label: Severity,
          widget: select,
          multiple: false,
          required: true,
          options:
            [
              { label: "Low Risk", value: "low" },
              { label: "Medium Risk", value: "medium" },
              { label: "High Risk", value: "medium" },
              { label: "Critical Risk", value: "critical" },
            ],
        }
      - { name: award, label: Award, required: false }
      - {
          name: wardens,
          label: Wardens,
          widget: relation,
          required: false,
          multiple: true,
          collection: "people",
          searchFields: ["name"],
          valueField: "id",
          displayFields: ["name"],
        }
      - { name: id, label: ID, widget: ncw-id }
